---
name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: "30 8 * * 3"

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Store private_key
        shell: bash
        env:
          ID_RSA: ${{ secrets.GH_KEY }}
        run: |
          mkdir -p ~/.ssh && 
          chmod 700 ~/.ssh && 
          echo "${ID_RSA}" > ~/.ssh/id_rsa && 
          chmod 600 ~/.ssh/id_rsa &&
          ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
      - name: Clone public repos for user (dryrun)
        run: ./github-clone.sh public --type users --name ckaserer --dryrun
      - name: Clone public repos for user
        run: ./github-clone.sh public --type users --name ckaserer
      - name: Clone public repos for org
        run: ./github-clone.sh public --type orgs --name gepardec
      - name: Clone all owned repos
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./github-clone.sh authenticated --ghtoken ${GH_TOKEN} --affiliation owner
      - name: Clone all owned repos matching a filter
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./github-clone.sh authenticated --ghtoken ${GH_TOKEN} --affiliation owner --filter ansible
  merge:
    name: Merge to master
    runs-on: ubuntu-latest
    needs: 
      - linter
      - functional-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
...